#!/bin/bash

set -e

OWNER=root
GPHOME=/usr/cloudberry-db

if [ "$1" = configure ]; then

  /sbin/ldconfig
fi

# add alternative location for the database binaries
ln -s /opt/greenplum-db-cb /usr/cloudberry-db