#!/bin/bash

set -e

OWNER=root
PXFVER=6
PXFHOME=/opt/greenplum-pxf-${PXFVER}
GPHOME=/opt/greenplum-db-6

chown -R ${OWNER}:${OWNER} ${PXFHOME}

echo -en '\ntrusted = true' >> ${GPHOME}/share/postgresql/extension/pxf.control
