#!/bin/bash

set -e

OWNER=root
PXFVER=1
PXFHOME=/opt/greenplum-pxf-${PXFVER}
GPHOME=/usr/cloudberry-db

chown -R ${OWNER}:${OWNER} ${PXFHOME}
# FIXME: build pxf extension for cloudberry
#chown    ${OWNER}:${OWNER} ${GPHOME}/lib/postgresql/pxf.so
chown    ${OWNER}:${OWNER} ${GPHOME}/share/postgresql/extension/pxf*

echo -en '\ntrusted = true' >> ${GPHOME}/share/postgresql/extension/pxf.control

# add alternative location for the database binaries
ln -s /opt/greenplum-pxf-1 /usr/cloudberry-pxf